app:
  port: 8080
  configuration: debug
  api-key: compositor

hypervisor:
  services:
    scripts-dir: ./app/tools/scripts/
    ports-service:
      db-path: ./ports-storage.db
    outbound-ip: 127.0.0.1
    container-create-attempts: 5
